module github.com/trilogy-group/randombugz

//Those are dependencies generated by getting a linter
require (
	github.com/go-resty/resty/v2 v2.1.0
	github.com/jaswdr/faker v1.0.2
	github.com/jessevdk/go-flags v1.4.0
	github.com/motemen/go-loghttp v0.0.0-20170804080138-974ac5ceac27
	github.com/motemen/go-nuts v0.0.0-20190725124253-1d2432db96b0 // indirect
	github.com/stretchr/testify v1.4.0 // indirect
)

go 1.13
